### ISSUE TITLE
Guild roster errors 

### ISSUE THREAD

**Issue by tilley697** [Budabot/Budabot#14]
"ERROR Guild xml file has no members! Aborting roster update."

not a coder but running a budabot server for new Anarchy online guild and it seems to be pulling information from old server.  Showing old names and levels including faction.

**Comment by bigwheels16** [comment]
This isn't fixable until Funcom brings up a service for the new server to get this information from.

**Comment by tilley697** [comment]
Ok thank you very much for the response.  I appreciate it greatly.

**Comment by jroovers** [comment]
FYI: updates about PoRK from funcom staff

**shaogens on 06/03/2019**  
> keep in mind the People of Rubi-Ka site only updates every 24-hours at most.

**(Odonoptera) Today at 15:06**  
> PoRK now tracks the new dimension yes, it will be labelled as RK6

At this time manually searching for characters doesn't show any rk6 characters yet (hence I also pasted the comment of shaogens)

**Comment by tilley697** [comment]
As I mentioned, I don’t know about programming.  Will this require changes
on our existing version of the bot or will it be something that works
itself out?

**Comment by jroovers** [comment]
@tilley697 welcome to github issues ^^, I'm just providing relevant information that might help solve this issue. Looking at the code the service call to PoRK does include a reference to dimension (rk6 is what we need) and a reference to your bot's guild. I'm assuming this will work once funcom successfully updates PoRK. Wether we need to do something to update our bots? We'll know when we know. 

I'm not a contributor to the code so my knowledge is very limited but my reply was mainly directed at bigwheels16 who is a main contributor.

**Comment by tilley697** [comment]
Awesome, I appreciate your responses as they are informative and allow me
to pass on updates to my org mates.  Thank you for your contribution.

**Comment by bigwheels16** [comment]
The released version of Budabot 4 will not work with the new PoRK even when they get it working.  I have added an update to the Budabot repository that fixes this, but given that I am not supporting Budabot anymore there won't be a release with it so if you want it you'll have to download from Github directly.

I have written Tyrbot (https://github.com/Budabot/Tyrbot) which does support the new server, once they get it fixed.  If you need help getting this set up feel free to join the discord: https://discord.gg/2x9WesJ

**Comment by tilley697** [comment]
Awesome!!!
