### ISSUE TITLE
Deprecated: Non-static method in PHP 5.6.x

### ISSUE THREAD

**Issue by RonnyJ** [Budabot/Budabot#6]
After my server provider upgraded to PHP 5.6.14, my bot is giving this error:

> Deprecated: Non-static method Budabot\Core\xml::spliceData() should not be called statically, assuming $this from incompatible context in /usr/home/user/shell/budabot/core/PLAYER_LOOKUP/GuildManager.class.php on line 68
> budabot Deprecated Non-static method

According to [Deprecated features in PHP 5.6.x](http://php.net/manual/en/migration56.deprecated.php) there are changes in PHP 5.6.x affecting Budabot.

I can choose between PHP 5.5 and 5.6 on my server, so I opted for 5.5 for now which fixed the issue for me.

**Comment by bigwheels16** [comment]
I committed 6a3b110377959d44270f24370523b644d3d210d4 which should address this issue, at least in this particular spot.  Let me know if you find this message in any other code.
