### ISSUE TITLE
APIController - Operation not permitted (0)

### ISSUE THREAD

**Issue by RonnyJ** [Budabot/Budabot#7]
I just noticed I was getting this error when bot is starting:

APIController - Operation not permitted (0)

The error message comes right after "All Systems ready!"

Happens both on PHP 5.5 and 5.6.

**Comment by bigwheels16** [comment]
Can you take a look in ./logs/<botname>.5/php_errors.log and see if there is any more information about this error?  Without knowing where exactly in the code it's happening, it will be pretty hard to track down, and I don't have PHP 5.5 installed to reproduce this.

**Comment by RonnyJ** [comment]
There is nothing else about this error in the logs beside that one line. 

Is there a debug function for Budabot which gives more output that I can run ?

**Comment by bigwheels16** [comment]
In ./conf/log4php.xml, on line 56 you should see this line: <level value="INFO" />

If you change it to: <level value="DEBUG" /> and then [re]start the bot, it will give you the debug output.  I will need the 50 or so lines before and after the error message.

**Comment by RonnyJ** [comment]
You forgot to add what to change it to, so I changed it to DEBUG and started the bot. Hope that was right.

Here is the error output from the logfile:

```
Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'whoiscontroller.recordCharIds' for event type 'allpackets'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'whoiscontroller'
Tue Feb 16 00:55:38 2016 DEBUG Budabot - AOCP_BUDDY_ADD => sender: 'Nemonstrous' status: '0'
Tue Feb 16 00:55:38 2016 DEBUG Budabot - Nemonstrous logged off
Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'guildcontroller.orgMemberLogoffMessageEvent' for event type 'logoff'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'guildcontroller'
Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'guildcontroller.orgMemberLogoffRecordEvent' for event type 'logoff'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'guildcontroller'
Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'irccontroller.logoffEvent' for event type 'logoff'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'irccontroller'
Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'onlinecontroller.recordLogoffEvent' for event type 'logoff'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'onlinecontroller'
Tue Feb 16 00:55:38 2016 DEBUG SQL - DELETE FROM `online` WHERE `name` = ? AND `channel_type` = ? AND added_by = 'aoobot' - Array
(
    [0] => Nemonstrous
    [1] => guild
)

Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'orglistcontroller.orgMemberLogoffEvent' for event type 'logoff'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'orglistcontroller'
Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'relaycontroller.relayLogoffMessagesEvent' for event type 'logoff'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'relaycontroller'
Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'trackercontroller.trackLogoffEvent' for event type 'logoff'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'trackercontroller'
Tue Feb 16 00:55:38 2016 DEBUG EventManager - Executing handler 'whoiscontroller.logoffEvent' for event type 'logoff'
Tue Feb 16 00:55:38 2016 DEBUG Registry - Requesting instance for 'whoiscontroller'
Tue Feb 16 00:55:39 2016 DEBUG EventManager - Executing connected events
Tue Feb 16 00:55:39 2016 DEBUG EventManager - Executing handler 'systemcontroller.onConnectEvent' for event type 'connect'
Tue Feb 16 00:55:39 2016 DEBUG Registry - Requesting instance for 'systemcontroller'
Tue Feb 16 00:55:39 2016 DEBUG Budabot - 
```

**Comment by bigwheels16** [comment]
Oh sorry, I forgot to escape the XML so it wasn't showing up.  But yeah, "DEBUG" was correct.   

Anyway, I don't see the error in your output.  I need to see the 50 lines before the error, the error itself, and then 50 lines after.  You can get the full output from the logfile at /logs/_botname_.5/budabot_2016-02.log

**Comment by RonnyJ** [comment]
It seems like the pasted text was too long to be put in code brackets. I attached the cutout of the log as txt-file in my previous post.

**Comment by bigwheels16** [comment]
ok thanks, I'll go through that and see if I can figure out what the deal is

**Comment by bigwheels16** [comment]
ok so I upgraded PHP to 5.6 and tested on Windows and didn't get the error.  And I made sure the API_MODULE was enabled.

I don't have a Linux system with PHP 5.6 installed to test against.  I would guess it's a permissions problem and Budabot isn't running as a user that has permissions to listen on a port, which is what the API_MODULE does.  It's unlikely that you are using the API_MODULE so I would do !config API_MODULE and then disable the connect event and that should stop the error from happening.  It's disabled by default, so someone would have had to enable it.

I intend to remove the API_MODULE from the next version of Budabot since it's not used at all that I am aware of, and if you need that functionality, the HTTP_SERVER_MODULE is a better option.

**Comment by RonnyJ** [comment]
You were right. For some reason, the API_MODULE was enabled. And Budabot does not have permission to listen on the specified port either in my firewall config.

I have disabled API_MODULE now, and the error message is gone.

Thank you so much for spending time troubleshooting this.

**Comment by bigwheels16** [comment]
no problem.  glad we got it figured out.
